In [32]:
## Import required modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import datetime as dt

In [33]:
## Load the dataset
df=pd.read_csv("sales_data.csv")
print("Data loaded successfully!")

## Show basic structure
print(df.head())

Data loaded successfully!
         Date  Order ID  Customer Name Product Category Product Name  \
0    9/3/2024  ORD10000    Julia Adams         Clothing        Jeans
1  12/19/2024  ORD10001   George Brown            Books  Non-Fiction
2   1/26/2025  ORD10002    Julia Adams           Beauty      Perfume
3   11/2/2024  ORD10003      Ian Black         Clothing       Jacket
4   10/3/2024  ORD10004  Charlie Davis           Beauty     Lipstick

   Quantity Sold  Unit Price  Total Revenue Payment Method Delivery Status  \
0              5      493.44        2467.20           Cash       Delivered
1              4      246.75         987.00         PayPal       Delivered
2              5      336.56        1682.80         PayPal       Delivered
3              5      193.58         967.90           Cash       Delivered
4              5      282.25        1411.25    Credit Card       Delivered

   Unnamed: 10 Unnamed: 11  Unnamed: 12
0          NaN         NaN          NaN
1          NaN         NaN          NaN
2          NaN         NaN          NaN
3          NaN         NaN          NaN
4          NaN         NaN          NaN

In [34]:
# Drop empty/unused columns if they exist
cols_to_drop = ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
existing_cols = [col for col in cols_to_drop if col in df.columns]
df.drop(columns=existing_cols, inplace=True)
print(f"Dropped columns: {existing_cols if existing_cols else 'None to drop'}")

df.head()

Dropped columns: ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

,Date,Order ID,Customer Name,Product Category,Product Name,Quantity Sold,Unit Price,Total Revenue,Payment Method,Delivery Status
0,9/3/2024,ORD10000,Julia Adams,Clothing,Jeans,5,493.44,2467.20,Cash,Delivered
1,12/19/2024,ORD10001,George Brown,Books,Non-Fiction,4,246.75,987.00,PayPal,Delivered
2,1/26/2025,ORD10002,Julia Adams,Beauty,Perfume,5,336.56,1682.80,PayPal,Delivered
3,11/2/2024,ORD10003,Ian Black,Clothing,Jacket,5,193.58,967.90,Cash,Delivered
4,10/3/2024,ORD10004,Charlie Davis,Beauty,Lipstick,5,282.25,1411.25,Credit Card,Delivered

In [35]:
# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])
print("Converted 'Date' column to datetime.")

Converted 'Date' column to datetime.

In [36]:
# Remove duplicate rows if any
initial_shape = df.shape
df.drop_duplicates(inplace=True)
final_shape = df.shape
print(f"Removed duplicates: {initial_shape[0] - final_shape[0]} rows dropped.")

Removed duplicates: 0 rows dropped.

In [37]:
## Standardize column names (lowercase & underscores)
df.columns = df.columns.str.lower().str.replace(' ', '_')
print("Standardized column names.")

df.head()

Standardized column names.

,date,order_id,customer_name,product_category,product_name,quantity_sold,unit_price,total_revenue,payment_method,delivery_status
0,2024-09-03,ORD10000,Julia Adams,Clothing,Jeans,5,493.44,2467.20,Cash,Delivered
1,2024-12-19,ORD10001,George Brown,Books,Non-Fiction,4,246.75,987.00,PayPal,Delivered
2,2025-01-26,ORD10002,Julia Adams,Beauty,Perfume,5,336.56,1682.80,PayPal,Delivered
3,2024-11-02,ORD10003,Ian Black,Clothing,Jacket,5,193.58,967.90,Cash,Delivered
4,2024-10-03,ORD10004,Charlie Davis,Beauty,Lipstick,5,282.25,1411.25,Credit Card,Delivered

In [38]:
# Check and correct total revenue calculation
# If there's a mismatch, we overwrite with correct calculation

df['calculated_revenue'] = df['quantity_sold'] * df['unit_price']
mismatch_count = (df['total_revenue'] != df['calculated_revenue']).sum()
if mismatch_count > 0:
    df['total_revenue'] = df['calculated_revenue']
    print(f"Found and fixed {mismatch_count} mismatched revenue rows.")
else:
    print("All revenue calculations are correct.")
df.drop(columns='calculated_revenue', inplace=True)

Found and fixed 53 mismatched revenue rows.

In [39]:
# Save the cleaned data
df.to_csv('sales_data_cleaned.csv', index=False)
print("Cleaned data saved to 'sales_data_cleaned.csv'.")

Cleaned data saved to 'sales_data_cleaned.csv'.